oomall:
  host: 47.97.26.168
  port: 8899
  user: 1940203832
  password: 123456
  adminuser: nan
  adminpassword: nan123
  norightuser: oomall
  norightpassword: oomall

logging:
  level:
    org.springframework: info