oomall:
  host: 47.96.159.71
  port: 8899
  user: 1940203832
  password: 123456
  adminuser: hi
  adminpassword: 123456
  norightuser: wowoto
  norightpassword: 123456

logging:
  level:
    org.springframework: info