oomall:
  host: 47.100.32.48
  port: 8400
  user: 55944411881
  password: 123456
  adminuser: admin1
  adminpassword: admin1
  norightuser: 1
  norightpassword: 2

spring:
  datasource:
    url: jdbc:mysql://148.70.28.112:3306/wowomall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: wowoto
    password: zqhlovekly

    driver-class-name: com.mysql.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  redis:
    host: 106.15.92.198
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000