oomall:
  host: 106.15.92.5
  port: 9527
  user: 1940203832
  password: 123456
  adminuser: 111
  adminpassword: 222
  norightuser: nan123
  norightpassword: 321

logging:
  level:
    org.springframework: info