oomall:
  host: 106.15.92.5
  port: 9527
  user: 49404524964
  password: 123456
  adminuser: 123
  adminpassword: 321
  norightuser: 111
  norightpassword: 222

logging:
  level:
    org.springframework: debug