oomall:
  host: 139.196.253.120
  port: 8898
  user: 1940203832
  password: 123456
  adminuser: hi
  adminpassword: 123456
  norightuser: wowoto
  norightpassword: 123456

logging:
  level:
    org.springframework: info